require('user.plugins.custom.adjust')
require('user.plugins.custom.banner_column')
require('user.plugins.custom.base_check')
require('user.plugins.custom.base_row')
require('user.plugins.custom.combine')
require('user.plugins.custom.diff_score')
require('user.plugins.custom.executables')
require('user.plugins.custom.generation')
require('user.plugins.custom.in2')
require('user.plugins.custom.indent')
require('user.plugins.custom.init_clean')
require('user.plugins.custom.layout')
require('user.plugins.custom.nets')
require('user.plugins.custom.norank')
require('user.plugins.custom.number')
require('user.plugins.custom.pos_spec_conversion')
require('user.plugins.custom.rank_table')
require('user.plugins.custom.region')
require('user.plugins.custom.series')
require('user.plugins.custom.skip')
require('user.plugins.custom.split_base')
require('user.plugins.custom.state_fips')
require('user.plugins.custom.sum_init')
require('user.plugins.custom.summary_setup')
require('user.plugins.custom.t1001')
require('user.plugins.custom.titles')
require('user.plugins.custom.uncle_syntax')
require('user.plugins.custom.underline')
require('user.plugins.custom.weight_sum')
require('user.plugins.custom.weight_tables')


-- replace 'mymodule' with the actual path to your module
vim.api.nvim_set_keymap('n', '<M-z>', ':lua require("user.plugins.custom.indent").indent()<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<M-d>', ':lua require("user.plugins.custom.pos_spec_conversion").posSpecConversion()<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<M-f>', ':lua require("user.plugins.custom.uncle_syntax").uncleSyntax()<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<M-g>', ':lua require("user.plugins.custom.uncle_syntax").combFix()<CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<M-i>', ':lua require("user.plugins.custom.in2").indent()<CR>', { noremap = true, silent = true })
