
local keymap = vim.api.nvim_set_keymap
keymap('n', '<leader>in', ':lua require("user.uncle.indent").indent()<CR>', { noremap = true, silent = true, desc = "Uncle: Indent" })
keymap('n', '<leader>ds', ':DiffScore<CR>', { noremap = true, silent = true, desc = "Uncle: Difference score" })
keymap('n', '<leader>k', ':lua require("user.uncle.uncle_syntax").uncleSyntax()<CR>', { noremap = true, silent = true, desc = "Uncle: QX-1 syntax" })
keymap('n', '<leader>j', ':lua require("user.uncle.uncle_syntax").combFix()<CR>', { noremap = true, silent = true, desc = "Uncle: QX:1 syntax" })
keymap('n', '<leader>ii', ':lua require("user.uncle.in2").indent()<CR>', { noremap = true, silent = true, desc = "Uncle: &IN2" })
keymap('n', '<leader>bc', ':lua require("user.uncle.banner_column").bannerColumn()<CR>', { noremap = true, silent = true, desc = "Uncle: Insert banner columns" })
keymap('n', '<leader>rr', ':lua require("user.uncle.r_row").rRow()<CR>', { noremap = true, silent = true, desc = "Uncle: Insert R Row" })
keymap('n', '<leader>u', ':lua require("user.uncle.underline").underline()<CR>', { noremap = true, silent = true, desc = "Uncle: Underline" })
keymap('n', '<leader>p', ':lua require("user.uncle.norank").noRank()<CR>', { noremap = true, silent = true, desc = "Uncle: No rank" })
keymap('n', '<leader>or', ':Rank<CR>', { noremap = true, silent = true, desc = "Uncle: O Rank" })
keymap('n', '<leader>sb', ':SplitBase<CR>', { noremap = true, silent = true, desc = "Uncle: Split Base" })
keymap('n', '<leader>si', ':SumInit<CR>', { noremap = true, silent = true, desc = "Uncle: Summmary initialize" })
keymap('n', '<leader>br', ':BaseRow<CR>', { noremap = true, silent = true, desc = "Uncle: Base Row" })
keymap('n', '<leader>ic', ':InitClean<CR>', { noremap = true, silent = true, desc = "Uncle: Initial Cleanup" })
keymap('n', '<leader>n', ':Nets<CR>', { noremap = true, silent = true, desc = "Uncle: Nets" })
keymap('n', '<leader>q', ':QualRow<CR>', { noremap = true, silent = true, desc = "Uncle: Qualifier Row" })
keymap('n', '<leader>wp', ':WeightProduct<CR>', { noremap = true, silent = true, desc = "Uncle: Weight Product" })
keymap('n', '<leader>ws', ':WeightSum<CR>', { noremap = true, silent = true, desc = "Uncle: Weight Sum" })
keymap('n', '<leader>wt', ':WeightTables<CR>', { noremap = true, silent = true, desc = "Uncle: Weight Tables" })
